### ISSUE TITLE
Tests are already passing for the entire “Initializers and Properties” section

### ISSUE THREAD

**Issue by mohhossain** [learn-co-curriculum/python-p3-mock-challenge-coffee-shop#1]
### Canvas Link

https://learning.flatironschool.com/courses/6329/assignments/239681

### Concern

Out of 24 tests, 12 tests are already passing. And these tests are part of the deliverables that students actually need to finish.  The tests don't raise exceptions where they should. For example, 

`def test_name_is_string(self):
        '''coffee is initialized with a name of type str'''
        coffee = Coffee("Mocha")
        assert (isinstance(coffee.name, str))`

This test set the name str and checks if it is a str but doesn't raise any exception when it any other types are given. 
There are 12 instances of this kind of errors.

**Comment by professor-ben** [comment]
Hi Mohammad,

We're taking a look at this one now- a couple notes first, though.

We provided students with a good deal of starter code in these, alongside some tests to show that the starter code was accomplishing what it was supposed to. These tests can break depending on how you modify things later on- just a natural part of development.

That being said, some of these tests are not doing very much. We're going to condense and remove a few of them for future students.

Thanks for reporting this!
Ben

**Comment by linda-seiter** [comment]
fixed #3
